name: Analizar y Desplegar - Lab Clínico

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_PROJECT_NAME: 'labclinico2025'
  APP_CONTAINER_NAME: 'springboot_backend'
  SONAR_HOST_URL: 'http://localhost:9000'
  SONAR_TOKEN: 'squ_4d43d0a4c06e2c4687cb9b2a2a9f423cb95451d0'
jobs:
  analyze-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Clonar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar el backend
        run: mvn -B clean package -DskipTests

      - name: Analizar con SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=lab-clinico \
            -Dsonar.projectName="Lab Clinico" \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }}

      - name: Desplegar con Docker Compose
        run: |
          echo "🧹 Limpiando contenedores anteriores..."
          docker compose -p ${{ env.DOCKER_PROJECT_NAME }} down -v --remove-orphans || true

          echo "🏗️ Construyendo e iniciando contenedores..."
          docker compose -p ${{ env.DOCKER_PROJECT_NAME }} up -d --build

          echo "🔍 Contenedores activos:"
          docker compose -p ${{ env.DOCKER_PROJECT_NAME }} ps

          echo "📄 Logs del backend:"
          docker logs --tail 100 ${{ env.APP_CONTAINER_NAME }}
